const columns = [
  {
    Header: ["CHOOSE YOUR PLAN"],
    accessor: "col1", // accessor is the "key" in the data
  },
  {
    Header: ["Financial Literacy", "For Beginners"],
    accessor: "col2",
  },
  {
    Header: ["SOIC Complete Investor", "For Fundamental Investors"],
    accessor: "col3",
  },
  {
    Header: ["SOIC Membership", "For Intelligent Investors"],
    accessor: "col4",
  },
  {
    Header: ["SOIC Mentorship", "Only available for 3 Students per year"],
    accessor: "col5",
  },
];

const data = [
  {
    col1: "FEATURES:",
    col2: "INR 9,999 /yr",
    col3: "INR 11,999 /yr",
    col4: "INR 14,999 /yr",
    col5: "INR 1,19,999 /yr",
  },
  {
    col1: "",
    col2: "INR 6,999 /yr",
    col3: "INR 8,999 /yr",
    col4: "INR 11,999 /yr",
    col5: "INR 99,999 /yr",
  },
  {
    col1: "Create Your Own Financial Plan",
    col2: true,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Nifty Wealth Creation",
    col2: true,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Pick Your Own Mutual Funds",
    col2: true,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Insurance",
    col2: true,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Alternate Investments (Gold, Silver etc)",
    col2: true,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Balance Sheet Analysis",
    col2: false,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Cash Flow Analysis",
    col2: false,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "P&L Statement Analysis",
    col2: false,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Ratio Analysis",
    col2: false,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Annual Report Analysis",
    col2: false,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Forensic Analysis",
    col2: false,
    col3: true,
    col4: true,
    col5: true,
  },
  {
    col1: "Live Classes",
    col2: false,
    col3: false,
    col4: true,
    col5: true,
  },
  {
    col1: "How to Value to a Company",
    col2: false,
    col3: false,
    col4: true,
    col5: true,
  },
  {
    col1: "When to Buy and Sell",
    col2: false,
    col3: false,
    col4: true,
    col5: true,
  },
  {
    col1: "Sectoral Analysis",
    col2: false,
    col3: false,
    col4: true,
    col5: true,
  },
  {
    col1: "Technical Analysis for Long Term Investors",
    col2: false,
    col3: false,
    col4: true,
    col5: true,
  },
  {
    col1: "Master Class with India's Best Investors",
    col2: false,
    col3: false,
    col4: true,
    col5: true,
  },
  {
    col1: "Personal Mentorship under Ishmohit",
    col2: false,
    col3: false,
    col4: false,
    col5: true,
  },
  {
    col1: "",
    col2: "https://rzp.io/l/qr7VQiZF",
    col3: "https://rzp.io/l/hPNme16",
    col4: "https://rzp.io/l/EBK9eL2",
    col5: "https://rzp.io/l/JedScWLMvT",
  },
];
export { data, columns };
